import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";

import SideMenu from "./_components/SideMenu";
import { authOptions } from "@/lib/auth-options";

export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {

    const session = await getServerSession(authOptions);

    if (!session || !session.user) {
        redirect("/login");
    }

    return <main className="h-dvh w-full flex flex-row items-start bg-slate-100 p-5 gap-5">
        <aside className="flex-grow bg-red-400 h-full rounded-md max-w-64 min-w-64">
            <SideMenu />
        </aside>
        <section className="flex-grow bg-white h-full rounded-md p-10">
            {children}
        </section>
    </main>;

}
